#ifndef GLSLSCENE_GL_VERSION_H
#define GLSLSCENE_GL_VERSION_H

//#define GLSLSCENE_USE_GLAD
#define GLSLSCENE_USE_GLEW


#ifdef GLSLSCENE_USE_GLEW
	#ifdef GLSLSCENE_USE_GLAD
		#undef GLSLSCENE_USE_GLAD
	#endif
#endif

#endif //GLSLSCENE_GL_VERSION_H
